name: Reservation Reminder

on:
  schedule:
    - cron: "" # runs at 7:30, 9:30, â€¦ UTC
  workflow_dispatch: # optional manual trigger

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run reminder script
        env:
          NODE_ENV: production
        run: |
          curl -L -v -X GET https://danloski.com/api/reservation-reminders
